# Copyright 2025 KU Leuven.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Author: Giuseppe Sarda <giuseppe.sarda@esat.kuleuven.be>

[workspace]
authors = ["Giuseppe Maria Sarda <giuseppe.sarda16@gmail.com>"]
channels = ["conda-forge", "pypi"]
name = "lagd"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.9"
rust = "*"
requests = "*"
mako = "*"
pyyaml = "*"
tabulate = "*"
yapf = "*"
mkdocs = "*"
mkdocs-material = "*"
flatdict = "*"

# Exstra dependencies for tclint
importlib-metadata = "==6.8.0"
pathspec = "==0.11.2"

[pypi-dependencies]
setuptools = "*"
hjson = "*"
markdown-grid-tables = "*"
tclint = "==0.4.2"